version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped

  # Optional: Add a database service
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: sentiment_analysis
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: