services:
  - type: web
    name: youtube-sentiment-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('wordnet'); nltk.download('punkt')"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
    healthCheckPath: /